To fix the below issue in the production. Changed to use LinkedHashSet instead of TreeSet.
   1. Click "Data Sets"
   2. Click "Next" link
   3. On page 2 of results, click "caTissue_Suite" link
   4. Receive ClassCastException:

    Time: Mar 2, 2011 9:47:27 AM
    Handler: gov.nih.nci.cagrid.portal.portlet.browse.BrowseViewDetailsController
    Exception: java.lang.ClassCastException